// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// IMPORTANT for Supabase:
// DATABASE_URL  = pgbouncer URL (port 6543) — used at runtime by the app
// DIRECT_URL    = direct Postgres URL (port 5432) — used for migrations/db push
//
// Add to .env:
// DIRECT_URL="postgresql://postgres.nluwzalipfaacmjcctxp:PASSWORD@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for schema migrations (bypasses pgbouncer)
    // Fall back to DATABASE_URL if DIRECT_URL not set
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});

